In [47]:
!pip install pandas 
!pip install scikit-learn

/bin/bash: line 1: /home/rhuan/rhuan/coding/python/jupyter_lab/ipynb_ai_studies/venv_ai_study/bin/pip: cannot execute: required file not found

/bin/bash: line 1: /home/rhuan/rhuan/coding/python/jupyter_lab/ipynb_ai_studies/venv_ai_study/bin/pip: cannot execute: required file not found

In [48]:
import pandas as pd

It is important to read the raw .csv filein order to work
We'll only need the columns "movieId" and "title"

In [49]:
ds_movies = pd.read_csv("https://raw.githubusercontent.com/krishnaik06/Recommendation_complete_tutorial/refs/heads/master/KNN%20Movie%20Recommendation/movies.csv")
ds_movies = ds_movies[["movieId","title"]]
ds_movies

      movieId                                      title
0           1                           Toy Story (1995)
1           2                             Jumanji (1995)
2           3                    Grumpier Old Men (1995)
3           4                   Waiting to Exhale (1995)
4           5         Father of the Bride Part II (1995)
...       ...                                        ...
9737   193581  Black Butler: Book of the Atlantic (2017)
9738   193583               No Game No Life: Zero (2017)
9739   193585                               Flint (2017)
9740   193587        Bungo Stray Dogs: Dead Apple (2018)
9741   193609        Andrew Dice Clay: Dice Rules (1991)

[9742 rows x 2 columns]

In [50]:
ds_rating = pd.read_csv("https://raw.githubusercontent.com/krishnaik06/Recommendation_complete_tutorial/refs/heads/master/KNN%20Movie%20Recommendation/ratings.csv")
ds_rating = ds_rating[["userId","movieId","rating"]]
ds_rating

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

Now we merge the two data_frame into one joining the movieId

In [51]:
dataframe = pd.merge(ds_movies,ds_rating, on="movieId")
dataframe

        movieId                                      title  userId  rating
0             1                           Toy Story (1995)       1     4.0
1             1                           Toy Story (1995)       5     4.0
2             1                           Toy Story (1995)       7     4.5
3             1                           Toy Story (1995)      15     2.5
4             1                           Toy Story (1995)      17     4.5
...         ...                                        ...     ...     ...
100831   193581  Black Butler: Book of the Atlantic (2017)     184     4.0
100832   193583               No Game No Life: Zero (2017)     184     3.5
100833   193585                               Flint (2017)     184     3.5
100834   193587        Bungo Stray Dogs: Dead Apple (2018)     184     3.5
100835   193609        Andrew Dice Clay: Dice Rules (1991)     331     4.0

[100836 rows x 4 columns]

Now, in order to pivot the dataframe, we'll put userId as the df index, and each title will be a column, having the rating as value. We'll create an 2x2 matrix where we can see which person gave each rating for each movie. fillna() will substitute the NaN for 0

In [52]:
df_recommender = dataframe.pivot_table(index="userId", columns="title", values= "rating").fillna(0)
df_recommender

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.5,3.5,0.0,0.0,0.0
609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,...,0.0,4.0,3.5,3.0,0.0,0.0,2.0,1.5,0.0,0.0

Now we find the K-Nearest Neighbours (KNN algorithm), so we can create the recommendations

In [53]:
from sklearn.neighbors import NearestNeighbors

#hyper parameters is what adjust the learning model
#the common parameters are our data in the dataframe created after the pivot
modelo_knn = NearestNeighbors(metric='cosine')
modelo_knn.fit(df_recommender) #fit will find the nearest neighbours

NearestNeighbors(metric='cosine')

df_recommender.iloc(idx_user) will return a Serie, an array with only 1 dimension
the model need a 2D array, so we use the array.reshape(1, -1) function. When it is (1, -1) we have a 2D in horizontal direction, while with (-1, 1) we have a 2D in vertical direction

In [54]:
# let's recommend something to the user 230
# When we call the model, we need to know the K distance and who is the neighbours index
idx_user = 230 # the 230º user, not the real index

distance, neighbour_index = modelo_knn.kneighbors(df_recommender.iloc[idx_user].values.reshape(1, -1),
                                                  n_neighbors=3)

/home/rhuan/rhuan/coding/python/jupyter_lab/ipynb_ai_studies/venv_ai_study/lib/python3.12/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(

The first neighbour is the own person, that's why we can ignore the "0" proximity. 
The results below are 2D arrays, but if we use the "flatten()" function, we can make it 1D again.

In [55]:
distance

array([[0.        , 0.45552938, 0.5850611 ]])

In [56]:
distance.flatten()

array([0.        , 0.45552938, 0.5850611 ])

In [57]:
neighbour_index

array([[230, 493,  29]])

In [58]:
user = df_recommender.index[idx_user] # get the user index

for i in range(0, len(distance.flatten())):
    if i == 0:
        print("User: {0}\n".format(user))
    else:
        print("Neighbour {0} has distance {1}".format(df_recommender.index[neighbour_index.flatten()[i]],distance.flatten()[i]))

User: 231

Neighbour 494 has distance 0.4555293756410078
Neighbour 30 has distance 0.5850611011819732

Diferenças do iloc e locate

In [59]:
display(df_recommender.iloc[230]) # get the 230º user, which is the index 231
print("----------------------")
display(df_recommender.loc[230]) # get the index 230

title
'71 (2014)                                   0.0
'Hellboy': The Seeds of Creation (2004)      0.0
'Round Midnight (1986)                       0.0
'Salem's Lot (2004)                          0.0
'Til There Was You (1997)                    0.0
                                            ...
eXistenZ (1999)                              0.0
xXx (2002)                                   0.0
xXx: State of the Union (2005)               0.0
¡Three Amigos! (1986)                        0.0
À nous la liberté (Freedom for Us) (1931)    0.0
Name: 231, Length: 9719, dtype: float64

----------------------

title
'71 (2014)                                   0.0
'Hellboy': The Seeds of Creation (2004)      0.0
'Round Midnight (1986)                       0.0
'Salem's Lot (2004)                          0.0
'Til There Was You (1997)                    0.0
                                            ...
eXistenZ (1999)                              0.0
xXx (2002)                                   0.0
xXx: State of the Union (2005)               0.0
¡Three Amigos! (1986)                        0.0
À nous la liberté (Freedom for Us) (1931)    0.0
Name: 230, Length: 9719, dtype: float64

We can compare what the user and the nearest neightbours watched, and when the neighbour gave a good rating and the user didn't watch, we recommend this movie. It can be automatized in a loop for each neighbour. 
We can pass each condition when calling the ds_titles in parentesis and & --> ds_title = ds_title[(condition1) & (condition2) & (condition3)]

In [60]:
ds_user = df_recommender.loc[user].to_frame() #make it a dataframe
ds_user

                                           231
title
'71 (2014)                                 0.0
'Hellboy': The Seeds of Creation (2004)    0.0
'Round Midnight (1986)                     0.0
'Salem's Lot (2004)                        0.0
'Til There Was You (1997)                  0.0
...                                        ...
eXistenZ (1999)                            0.0
xXx (2002)                                 0.0
xXx: State of the Union (2005)             0.0
¡Three Amigos! (1986)                      0.0
À nous la liberté (Freedom for Us) (1931)  0.0

[9719 rows x 1 columns]

In [61]:
next_neighbour = df_recommender.index[neighbour_index.flatten()[1]]
ds_neighbour = df_recommender.loc[next_neighbour].to_frame()
ds_neighbour

                                           494
title
'71 (2014)                                 0.0
'Hellboy': The Seeds of Creation (2004)    0.0
'Round Midnight (1986)                     0.0
'Salem's Lot (2004)                        0.0
'Til There Was You (1997)                  0.0
...                                        ...
eXistenZ (1999)                            0.0
xXx (2002)                                 0.0
xXx: State of the Union (2005)             0.0
¡Three Amigos! (1986)                      0.0
À nous la liberté (Freedom for Us) (1931)  0.0

[9719 rows x 1 columns]

In [62]:
ds_title = pd.merge(ds_user,ds_neighbour,on='title').sort_values(by=next_neighbour,ascending=False)
ds_title

                                   231  494
title
Terminator 2: Judgment Day (1991)  5.0  5.0
Saving Private Ryan (1998)         0.0  5.0
Matrix, The (1999)                 5.0  5.0
Aliens (1986)                      5.0  5.0
Braveheart (1995)                  0.0  5.0
...                                ...  ...
Friends with Money (2006)          0.0  0.0
Fright Night (1985)                0.0  0.0
Fright Night (2011)                0.0  0.0
Fright Night Part II (1988)        0.0  0.0
Fried Green Tomatoes (1991)        0.0  0.0

[9719 rows x 2 columns]

In [63]:
#next_neighbour and user are the real index(or name) for the nearest_neighbours_index list 
# we could recomend only those movies which the near neighbour gave > 3 of rating
ds_title_recommendation = ds_title[(ds_title[next_neighbour] > 3) & (ds_title[user]==0)].reset_index()
ds_title_recommendation

                                               title  231  494
0                         Saving Private Ryan (1998)  0.0  5.0
1                                  Braveheart (1995)  0.0  5.0
2                                   Gladiator (2000)  0.0  5.0
3                     Godfather: Part II, The (1974)  0.0  5.0
4  Good, the Bad and the Ugly, The (Buono, il bru...  0.0  4.0
5  Star Wars: Episode VI - Return of the Jedi (1983)  0.0  4.0

In [64]:
list(ds_title_recommendation.title[:5]) #make a .json list with the first five movies

['Saving Private Ryan (1998)',
 'Braveheart (1995)',
 'Gladiator (2000)',
 'Godfather: Part II, The (1974)',
 'Good, the Bad and the Ugly, The (Buono, il brutto, il cattivo, Il) (1966)']